name: Publish Packages on NPM
on:
  workflow_dispatch:
    inputs:
      commitMsg:
        description: Commit message for release
        required: false
        default: 'chore: release new version '
      bumpType:
        type: choice
        description: Bump Release
        required: true
        default: patch
        options:
          - major
          - minor
          - patch

jobs:
  publishing:
    name: Package Publishing
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org/'
          scope: '@vue-storefront'

      - name: Create .npmrc
        env:
          NODE_AUTH_TOKEN: '${{ secrets.NPM_TOKEN }}'
        run: |
          echo "shamefully-hoist=true" >> .npmrc\
          echo "auto-install-peers=true" >> .npmrc\
          echo "legacy-peer-deps=true" >> .npmrc\
          && echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc\
          && echo "@vue-storefront:registry=https://registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}">> .npmrc\

      - name: Install Packages
        uses: pnpm/action-setup@master
        with:
          node-version: '16'
          version: 7
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Get PNPM store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Fetch cached files
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Bump Version & Push
        run: |
          npx bumpp ${{ github.event.inputs.bumpType }} \
          package.json \
          packages/*/package.json \
          --commit "${{ github.event.inputs.commitMsg}}" \
          --push \
          --tag

      - name: Publish Package
        run: pnpm -r publish --access public
        env:
          NODE_AUTH_TOKEN: '${{ secrets.NPM_TOKEN }}'
